language: node_js
node_js:
  - 12

cache:
  npm: true
  directories:
    - ./node_modules

before_script:
  - npm install


deploy:
  - provider: script
    skip_cleanup: true
    script:
      npm run build ;
      echo "I am true, Deploy here..."
    on:
      branch: master

  